version: '3'
services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    container_name: NginxProxyManager
    restart: always
    ports:
      - 8181:8181
      - 80:8080
      - 443:4443
    volumes:
      - data:/config:rw
volumes:
  data:
