version: "3.1"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: Heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - data:/config
    ports:
      - 92:80
    restart: always
volumes:
    data:    
