version: '3.1'
services:
  plex:
    container_name: Plex
    image: plexinc/pms-docker
    restart: always
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=<claimToken>
    hostname: Plex
    network_mode: host
    volumes:
      - data:/config
      - transcode:/transcode
      - <path/to/media>:/data
    # pass in the Intel gpu for Intel Quicksync
    devices:
      - /dev/dri:/dev/dri
volumes:
    data:
    transcode:
