version: '3.1'

services:

  db:
    container_name: SQLServer2019
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: password
      TZ: Europe/Dublin
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql
      - /srv/drivepool/backup/:/mnt/backupsql
volumes:
    data:
