version: '3.1'
services:
  teamspeak:
    image: teamspeak
    container_name: Teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
    volumes:
      - data:/var/ts3server
volumes:
    data:
