version: "3"
services:
  watchtower:
    container_name: Watchtower
    image: containrrr/watchtower 
    environment:
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
