version: "3"
services:
  watchtower:
    container_name: Watchtower
    image: containrrr/watchtower
    restart: always
    command: --interval 86400
    environment:
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
